apiVersion: v1
kind: Service
metadata:
  labels:
    app: bot-service
  name: bot-service
  namespace: kube-ops

spec:
  ports:
    - name: 'bot-svc'
      nodePort: 31112
      port: 31112
      protocol: TCP
      targetPort: 31112
  selector:
    app: bot-service
  type: NodePort
