apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-service
  name: api-service
  namespace: kube-ops

spec:
  ports:
    - name: 'api-svc'
      nodePort: 31110
      port: 31110
      protocol: TCP
      targetPort: 31110
  selector:
    app: api-service
  type: NodePort
