apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    monitoring: prometheus
  namespace: kube-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: louis70109/chatops:v15
          ports:
            - containerPort: 31110
